### ISSUE TITLE
instance_deactivate_all seems to break application_surface?

### ISSUE THREAD

**Issue by BinarryCode** [GM82Project/gm82dx9#3]
I discovered this while trying to make a NES-style fade shader.
Here is a comparison with the line commented/uncommented:
![uncommented](https://github.com/GM82Project/gm82dx9/assets/53833277/6c96b549-abdc-4ab5-afd0-901d77ed00e1)

https://github.com/GM82Project/gm82dx9/assets/53833277/21217333-8f2a-483f-b9bc-cc5bf09750a3

![commented](https://github.com/GM82Project/gm82dx9/assets/53833277/06f0b2cf-1054-4d6d-a25b-b39a947be09d)

https://github.com/GM82Project/gm82dx9/assets/53833277/adeb3168-2f3a-4633-a129-971b6fea0350

**Comment by omicronrex** [comment]
fixed in 447756dbbd4f0e21b26347c0c0fe9bed5eac657f
