### ISSUE TITLE
gex compilation error

### ISSUE THREAD

**Issue by mothbrawl** [GM82Project/gm82dx9#4]
I downloaded the .gex from the actions tab after struggling to put it together, and whenever I load one of the example projects with the extension, I get the following error:

```
___________________________________________
COMPILATION ERROR in extension package Game Maker 8.2 DirectX9
Error in code at line 7:
       d3d_model_load(__m,buffer_make_pipe(__b))
                          ^
at position 25: Unknown function or script: buffer_make_pipe

```

I tried adding gm82net and gm82core, but still get the same problem. What should I do?

**Comment by omicronrex** [comment]
extension builds on github are outdated, look in the discord for a download link to all latest artifacts.
